import nextCoreWebVitals from 'eslint-config-next/core-web-vitals';
import nextTypescript from 'eslint-config-next/typescript';

export default [
  ...nextCoreWebVitals,
  ...nextTypescript,
  {
    rules: {
      '@typescript-eslint/no-unused-vars': [
        'warn',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_' },
      ],
      '@typescript-eslint/no-explicit-any': 'error',
      // React Compiler hints — útiles como pista pero no fallan el build.
      // Convertimos a warning para mantener la señal pero permitir merge.
      'react-hooks/set-state-in-effect': 'warn',
      'react-hooks/incompatible-library': 'warn',
      'react-hooks/component-hook-factories': 'warn',
      'react-hooks/static-components': 'warn',
    },
  },
  {
    // Tests E2E: parametrizamos casos donde Playwright o react-hook-form
    // requieren `any` legítimo (firmas dinámicas), y donde imports `@/...`
    // no son necesarios.
    files: ['e2e/**/*.ts', 'e2e/**/*.tsx'],
    rules: {
      '@typescript-eslint/no-explicit-any': 'off',
    },
  },
  {
    // Scripts CLI usan require/console.log abundantemente
    files: ['scripts/**/*.{ts,mts,mjs,js,cjs}'],
    rules: {
      '@typescript-eslint/no-require-imports': 'off',
      'no-console': 'off',
    },
  },
  {
    // Generated by content-collections, no auditamos
    ignores: [
      '.content-collections/**',
      '.next/**',
      'node_modules/**',
      'e2e/.results/**',
      'e2e/.auth/**',
      'playwright-report/**',
      'test-results/**',
      'drizzle/migrations/**',
      'public/**',
    ],
  },
];
